spring.application.name=mokopay-backeend

spring.datasource.url= jdbc:mysql://localhost:3306/mokopay_db?useSSL=false
spring.datasource.username= root
spring.datasource.password= monkila1234
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update

spring.profiles.active:dev
# spring.profiles.active:prod

# server.port= 9090
# server.address=192.168.1.84

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=providermail30@gmail.com
spring.mail.password=wggl eyeg upui snck
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB


supportNumber=+243816717846
jwtSecret = 43816717846jdjjsji43816717846jjejhjh43816717846hwjhjjhew43816717846hjjhdj43816717846
jwtExpirationMs = 86400000
jwtCookie =monkilatoken

apikey-firebase = MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCh4gz4fs5OHric\nDZCvyJC4AW6WNdjweNT1TXQZPQfufJTWRv76XcrO09FnTpZx9Pud7QYnPx5Mneqy\nVeOqQcvTjwN5NFF4utsFqNKBxcA4usG6A1T2yXyBk1ARmFtukdqZdVirMXVMthwy\n3OszgfJGb34OMUzc5o73lRZASIZ1NXUskzKksDw7cbr+qswDKbhxo6vdlcOWuTOt\nuS8Ps5atIVgH1qMzpNrlKUXgPe8tV2V64SLTCH6NsDSwYZrG3rNfY515ezZ3Oc1Q\nup+L/Klb6kIUJD4Y7VbSvfU6KA4NUkB4diK6125s0jsO3TU37CYadrM+uNrV639A\nvF65E5uRAgMBAAECggEAGrOopAx2hxg2JzdtmDEi/dbuoMQ9Bl1H8zZVYhxZBJN0\nEWwgfredzkPOFJY35pAcOM5x52NX4hdiMQxNwzWbI0hBsGpazek0W1ifcFxn+nOD\npOULzLErYkwkNuLEohZY0lsyxvofeQnI2PLrsNFMXyXgywKCxSUai+gBhZTw6MAn\naHhnYVlmAizK6eNsnNUTUtvmo9wTCxm5y08p7rUUrjUM1/bwW3p7vUBDxiY8fNrH\nlnUugUf7bLrYwOJ4gWhiDXWYYWUcOejuZVtc5bAGcjCkhx096fTmLOLEvVrCMXrh\nE8+qlefMuqpICJAb2EFaArT8e+HEGs+fl3qHuSTVqQKBgQDQdnApikgtV/f06AEA\nAfKe1DLJjFJSmozjLwYpqNEHAlWr13My2OdUxDV4XHld3m0Jlhf9vMQaMOhSOp8Q\nFTnvcEUk8io7emItscE6DKoLfBr6s7RTSm04IdCXlwbZGh1x2ZnfrvXPLPtLaimf\nck5HAkpqjwNk7gz5pCjZFn/GxwKBgQDGzGb1W7/uyUPA6ObubpXGrtd8QTC2G6bS\noB2DJ7mzcYoYuOU1F7+UP9VS4XPkc+x61xRV3EhalrMy7+Gsj84URDE7BvkhR9a3\nZAMluJxbzAiGO+DCnSz+ZO8ISQI95WXo8DafRfy/ERFdvl6CrQG1IQGg53Mm48FK\nAI7N94jS5wKBgQDOj31mfAI3BALLpxROmJ97aFKGycdM2J2gA5l8sC2nX1Xat9sL\nWEgpA17kS+Vq8RpkNFjDcUdzmGCsEjBI9G965WluSZM1anhcRNVtmtzoEmp9XpHh\nMk91HnSdsOX1O95PUMobDje9uRmsSZ7CwrXzwL5SRjGb0hIDT/m12oh0QwKBgC3u\ncCNkbXYYXmUl6qVQO57KKtN0pHKO9P5ZLDhvZ0KEiymnHp4jvIneLcWWfZZdClhf\ndT1ZRgZYJ1MvhW6/UxfvoYhH1ivQU1XP78I5Yzb6b0XEc+vDMPAeFfROGgx/AgrN\n5XDrVLg4k1CbeW6r1mcpFx08HKjxmmkks9n2xVAlAoGBAIBb3Rk3RLxPMg0BIRCQ\nExT+4N6Wa0zsS+Mwdec8bOnsJxA9xfnLrE1NleFRTv13ddVVoaS9Js6LLmozQ9yT\nniIJ1tS9V3x08WLCQBORAnZ40VrmF1PvPn4hY3iA05e2h8vhjoVAtK9m8Kh7QCyB\nDn3wSa6BIlcMC9jOIABJOCJ2